# -*- coding: utf-8 -*-
"""S3_to_Video.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-LXsRVGv4zyfZ7cHV0Cn4dHSjNHsVqr4
"""

#!pip install boto3
import boto3
import base64
import cv2
import numpy as np
import sys

print("started video creation")

AWS_ACCESS_KEY = sys.argv[2]
AWS_SECRET_ACCESS_KEY = sys.argv[3]
s3 = boto3.resource(
    service_name='s3',
    region_name='us-east-1',
    aws_access_key_id=AWS_ACCESS_KEY,
    aws_secret_access_key=AWS_SECRET_ACCESS_KEY
)

screenShare_bucket=s3.Bucket('secure-screen')
room_no=sys.argv[1]

prefix='images/{}/'.format(room_no)

key_dict=dict()

for bucket_object in screenShare_bucket.objects.filter(Prefix=prefix):
    obj_key=bucket_object.key
    key_dict[obj_key]=bucket_object.get()['Body'].read()

keys=list(key_dict.keys())

def custom_order(x):
  prox_val=int(x.split('.')[0].split('/')[-1])
  return prox_val

sorted_key_list=sorted(keys,key=custom_order)
sorted_body=[]
for key in sorted_key_list:
  sorted_body.append(key_dict[key])

def generate_buffer(s):
  jpg_original=base64.b64decode(s)
  return np.frombuffer(jpg_original, dtype=np.uint8)

def generate_video_from_strings(string_list):  
    frame = cv2.imdecode(generate_buffer(string_list[0]), flags=1)
    video_name= 'screen_recording.mp4'
    height, width, layers = frame.shape  

    fcc = cv2.VideoWriter_fourcc(*'MP4V')
    video = cv2.VideoWriter(video_name, fcc, 5, (width, height)) 
    for string in string_list: 
        video.write(cv2.imdecode(generate_buffer(string), flags=1)) 
    
    cv2.destroyAllWindows() 
    video.release()

generate_video_from_strings(sorted_body)

s3.meta.client.upload_file('screen_recording.mp4','secure-screen','videos/' + room_no +'/record.mp4')

screenShare_bucket.objects.filter(Prefix=prefix).delete()

